export const samplePosts = [
  {
    id: 1,
    image: "https://picsum.photos/seed/post1/800/600",
    category: "Tech",
    title: "The Future of AI",
    author: "John Doe",
    authorImage: "https://picsum.photos/seed/author1/100/100",
    description:
      "Artificial Intelligence is rapidly evolving. This article explores the potential impacts and advancements we can expect in the coming years.",
    date: "2023-05-20T10:30:00Z",
    tags: ["AI", "Technology", "Future"],
  },
  {
    id: 2,
    image: "https://picsum.photos/seed/post2/800/600",
    category: "Local",
    title: "The Benefits of Meditation",
    author: "Jane Smith",
    authorImage: "https://picsum.photos/seed/author2/100/100",
    description:
      "Discover how daily meditation can improve your mental health, reduce stress, and increase overall well-being.",
    date: "2023-05-21T14:45:00Z",
    tags: ["Meditation", "Local", "Health", "Wellness"],
  },
  {
    id: 3,
    image: "https://picsum.photos/seed/post3/800/600",
    category: "Environment",
    title: "Climate Change: A Global Crisis",
    author: "Emily Brown",
    authorImage: "https://picsum.photos/seed/author3/100/100",
    description:
      "An in-depth look at the current state of climate change, its impacts, and what we can do to mitigate its effects.",
    date: "2023-05-22T09:15:00Z",
    tags: ["Climate Change", "Environment", "Sustainability"],
  },
  {
    id: 4,
    image: "https://picsum.photos/seed/post4/800/600",
    category: "Tech",
    title: "The Rise of Remote Work",
    author: "Michael Johnson",
    authorImage: "https://picsum.photos/seed/author4/100/100",
    description:
      "How the pandemic has accelerated the shift towards remote work and its implications for the future of business.",
    date: "2023-05-23T16:20:00Z",
    tags: ["Remote Work", "Tech", "Future of Work"],
  },
  {
    id: 5,
    image: "https://picsum.photos/seed/post5/800/600",
    category: "Lifestyle",
    title: "Exploring World Cuisines",
    author: "Sarah Lee",
    authorImage: "https://picsum.photos/seed/author5/100/100",
    description:
      "A culinary journey through different cultures, exploring unique flavors and cooking techniques from around the globe.",
    date: "2023-05-24T12:00:00Z",
    tags: ["Food", "Travel", "Culture"],
  },
  {
    id: 6,
    image: "https://picsum.photos/seed/post6/800/600",
    category: "Business",
    title: "The Impact of Blockchain on Finance",
    author: "Robert Chen",
    authorImage: "https://picsum.photos/seed/author6/100/100",
    description:
      "Exploring how blockchain technology is revolutionizing the financial sector and its potential future applications.",
    date: "2023-05-25T11:30:00Z",
    tags: ["Blockchain", "Finance", "Technology"],
  },
  {
    id: 7,
    image: "https://picsum.photos/seed/post7/800/600",
    category: "Business",
    title: "Sustainable Business Practices",
    author: "Emma Watson",
    authorImage: "https://picsum.photos/seed/author7/100/100",
    description:
      "How companies are incorporating sustainability into their business models and the benefits of eco-friendly practices.",
    date: "2023-05-26T09:45:00Z",
    tags: ["Sustainability", "Business", "Environment"],
  },
  {
    id: 8,
    image: "https://picsum.photos/seed/post8/800/600",
    category: "Crime",
    title: "The Rise in Cybercrime: What You Need to Know",
    author: "David Miller",
    authorImage: "https://picsum.photos/seed/author8/100/100",
    description:
      "An analysis of the growing cybercrime trends, their impact on individuals and businesses, and how to protect yourself.",
    date: "2023-05-27T14:15:00Z",
    tags: ["Cybercrime", "Security", "Technology"],
  },
  {
    id: 10,
    image: "https://picsum.photos/seed/post10/800/600",
    category: "Entertainment",
    title: "The Evolution of Streaming Services",
    author: "Emma Thompson",
    authorImage: "https://picsum.photos/seed/author10/100/100",
    description:
      "How streaming services are changing the entertainment industry and what it means for traditional media.",
    date: "2023-05-28T10:00:00Z",
    tags: ["Streaming", "Media", "Technology"],
  },
  {
    id: 11,
    image: "https://picsum.photos/seed/post11/800/600",
    category: "Politics",
    title: "The Impact of Social Media on Modern Politics",
    author: "Alex Johnson",
    authorImage: "https://picsum.photos/seed/author11/100/100",
    description:
      "An exploration of how social media platforms are shaping political discourse and influencing election outcomes.",
    date: "2023-05-29T09:30:00Z",
    tags: ["Social Media", "Elections", "Democracy"],
  },
];